решены задачи 1-3
js-tasks-ru/jsbasic-20221215_andreitul pull request #3
Opened 2022-12-16 15:07 UTC by NewSky-Pes

2022-12-16 15:09 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-12-17 16:18 UTC, koalex requested changes
Исправить 2-3

2022-12-17 16:18 UTC, koalex commented on 2-module/3-task/index.js
>  let calculator = {
Эту задачу нужно решить через `this`, а не `calculator`. Исправить

2022-12-17 16:18 UTC, koalex commented on 2-module/3-task/index.js
> +    calculator.a = a;
```
this.a = a;
this.b  = b;
```

2022-12-17 18:15 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-12-17 18:19 UTC, NewSky-Pes commented on 2-module/3-task/index.js
>  let calculator = {
Исправил, заменив на this

2022-12-18 05:25 UTC, koalex approved these changes

2022-12-18 05:26 UTC, merged